#!/usr/bin/env tsx
/**
 * Generates 128×128 PNG thumbnails for every kind in the cube catalog.
 *
 * Prerequisites: the studio dev server must be running at
 *   http://localhost:5173 (run `pnpm dev` in packages/studio first).
 *
 * Output: packages/world/thumbnails/<kindId>.png
 *         packages/world/src/scenes/thumbnail-manifest.ts
 *
 * Usage: pnpm gen:thumbnails
 *
 * Skips kinds with category 'character'. On failure for a specific kind,
 * logs a warning and continues. Prints a summary at the end.
 */

import { chromium } from 'playwright';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { dirname } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));
const THUMBNAILS_DIR = path.resolve(__dirname, '../thumbnails');
const MANIFEST_PATH = path.resolve(__dirname, '../src/scenes/thumbnail-manifest.ts');
const DEV_SERVER = 'http://localhost:5173';
const CATALOG_URL = `${DEV_SERVER}/api/cube-kinds`;

interface CubeKindEntry {
  id: string;
  label: string;
  category: string;
}

async function fetchCatalog(): Promise<CubeKindEntry[]> {
  let res: Response;
  try {
    res = await fetch(CATALOG_URL, { signal: AbortSignal.timeout(5000) });
  } catch (err) {
    console.error(
      `\n[gen-thumbnails] ERROR: Could not reach the dev server at ${DEV_SERVER}.`,
      '\nMake sure the studio dev server is running:',
      '\n  pnpm --filter @officexr/studio dev\n',
    );
    process.exit(1);
  }
  if (!res.ok) {
    console.error(
      `[gen-thumbnails] ERROR: /api/cube-kinds returned ${res.status}.`,
      'Make sure the studio dev server is running.',
    );
    process.exit(1);
  }
  const json = (await res.json()) as { kinds?: CubeKindEntry[] };
  return json.kinds ?? [];
}

function writeManifest(generated: Array<{ id: string; filePath: string }>) {
  const entries = generated
    .map(({ id }) => `  '${id}': new URL('../../thumbnails/${id}.png', import.meta.url).href,`)
    .join('\n');

  const content = `// Auto-generated by pnpm gen:thumbnails — do not edit manually.
// Re-run \`pnpm gen:thumbnails\` after catalog edits or new asset-pack installs.

export const THUMBNAIL_MANIFEST: Record<string, string> = {
${entries}
};
`;
  fs.writeFileSync(MANIFEST_PATH, content, 'utf-8');
  console.log(`[gen-thumbnails] Wrote manifest to ${MANIFEST_PATH}`);
}

async function main() {
  // Ensure output directory exists.
  fs.mkdirSync(THUMBNAILS_DIR, { recursive: true });

  console.log(`[gen-thumbnails] Fetching catalog from ${CATALOG_URL}...`);
  const allKinds = await fetchCatalog();

  // Filter out 'character' category.
  const kinds = allKinds.filter((k) => k.category !== 'character');
  console.log(
    `[gen-thumbnails] ${allKinds.length} kinds total, ${allKinds.length - kinds.length} 'character' kinds skipped.`,
  );
  console.log(`[gen-thumbnails] Generating thumbnails for ${kinds.length} kinds...`);

  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();

  // Navigate to the Object editor with thumbnailMode=true
  const objectUrl = `${DEV_SERVER}/#object?thumbnailMode=true`;
  console.log(`[gen-thumbnails] Navigating to ${objectUrl}...`);
  await page.goto(objectUrl);

  // Wait for the page to stabilize (React rendered, catalog loaded)
  await page.waitForTimeout(2000);

  let successCount = 0;
  let failCount = 0;
  const generated: Array<{ id: string; filePath: string }> = [];

  for (const kind of kinds) {
    const outputPath = path.join(THUMBNAILS_DIR, `${kind.id}.png`);

    try {
      // Find the kind button by data-kind-id attribute
      const kindBtn = page.locator(`[data-kind-id="${kind.id}"]`);
      const count = await kindBtn.count();
      if (count === 0) {
        // Try expanding collapsed category sections first
        const collapseBtn = page.locator('button').filter({ hasText: kind.category });
        if ((await collapseBtn.count()) > 0) {
          await collapseBtn.first().click();
          await page.waitForTimeout(100);
        }

        const afterExpand = await kindBtn.count();
        if (afterExpand === 0) {
          console.warn(`[gen-thumbnails] WARN: kind "${kind.id}" not found in KindList. Skipping.`);
          failCount++;
          continue;
        }
      }

      // Click the kind to select it
      await kindBtn.first().click();

      // Wait for the preview to settle (GLTF load + render)
      await page.waitForTimeout(800);

      // Screenshot the canvas element
      const canvas = page.locator('canvas').first();
      if ((await canvas.count()) === 0) {
        console.warn(`[gen-thumbnails] WARN: No canvas found for kind "${kind.id}". Skipping.`);
        failCount++;
        continue;
      }

      await canvas.screenshot({ path: outputPath, omitBackground: true });
      generated.push({ id: kind.id, filePath: outputPath });
      successCount++;
      process.stdout.write('.');
    } catch (err) {
      console.warn(`\n[gen-thumbnails] WARN: Failed to generate thumbnail for "${kind.id}":`, err);
      failCount++;
    }
  }

  await browser.close();

  console.log(`\n[gen-thumbnails] Done. Generated ${successCount} thumbnails, ${failCount} failed.`);

  if (generated.length > 0) {
    writeManifest(generated);
  } else {
    console.warn('[gen-thumbnails] No thumbnails generated — manifest not written.');
  }
}

main().catch((err) => {
  console.error('[gen-thumbnails] Fatal error:', err);
  process.exit(1);
});
