/**
 * Thumbnail URL lookup for the cube catalog.
 *
 * The manifest is auto-generated by `pnpm gen:thumbnails` and committed
 * to the repo. Each entry uses `new URL(..., import.meta.url).href` so
 * Vite's asset pipeline hashes and processes the PNGs correctly.
 *
 * Returns null if no thumbnail exists for a given kind (e.g. kinds added
 * after the last thumbnail generation run, or before the first run).
 */
import { THUMBNAIL_MANIFEST } from './thumbnail-manifest.ts';

/**
 * Returns the Vite-resolved URL for a kind's pre-generated thumbnail PNG,
 * or null if no thumbnail exists for this kind.
 */
export function thumbnailUrlForKind(id: string): string | null {
  return THUMBNAIL_MANIFEST[id] ?? null;
}
