// Auto-generated by pnpm gen:thumbnails — do not edit manually.
// Re-run `pnpm gen:thumbnails` from the repo root after catalog edits or new asset-pack installs.
// This file is intentionally empty on first commit — run `pnpm gen:thumbnails` to populate it.

export const THUMBNAIL_MANIFEST: Record<string, string> = {};
